#**NUMPY - 1º Abrindo a Documentação da Biblioteca**

Procurar no motor de busca: NumPy

Procurar docomentação básica para inciantes

# **NUMPY - 2º Qual a diferença entre NumPy e listas?"**

Comparar performance entre list e array::

In [ ]:
import numpy as np
num_elementos = 1000000000
teste_memoria_lista = []
# for x in range (num_elementos):
#   teste_memoria_lista.append(num_elementos)

teste_memoria_array = np.arange(num_elementos) 

#**NUMPY - 3º Criar um arrays simples com numpy**

Utilizar:

.array/.zeros/.ones/.empty/.arrange/.linespace

In [ ]:
import numpy as np

print("Array criado com o método .array") 
print(np.array([2,3,4]))
print("Array criado com o método .zeros") 
print(np.zeros(10))
print("Array criado com o método .ones") 
print(np.ones(10))
print("Array criado com o método .empty") 
print(np.empty(10))
print("Array criado com o método .arange") 
print(np.arange(10))
print("Array criado com o método .linespace") 
print(np.linspace(0,40, num = 21))

#**NUMPY - 4º A importância de se definir os tipo de dado**

COMPARAR PERFORMANCE INT8 com FLOAT64

In [ ]:
import numpy as np
num_elementos = 1000000000
# teste_performance = np.ones(num_elementos)
teste_performance = np.ones(num_elementos, dtype = np.int8)
print(teste_performance)

[1 1 1 ... 1 1 1]


#**NUMPY - 5º Criando um vetor de números randômicos**

In [ ]:
import numpy as np
rng = np.random.default_rng()
print(rng.random(3))

#**NUMPY - 6º Vetor vs Matriz vs Tensor**

In [ ]:
import numpy as np
rng = np.random.default_rng()
print("\n\nEste é um vetor 1's de tamanho 10")
vetor = rng.random((3))
print(vetor)
print("\n\nEsta é uma matriz 1's de tamanho 10")
matriz = rng.random((3,3))
print(matriz)
print("\n\nEste é um tensor 1's de tamanho 10")
tensor = rng.random((3,3,3))
print(tensor)



Este é um vetor 1's de tamanho 10
[0.91573005 0.46239016 0.32541949]


Esta é uma matriz 1's de tamanho 10
[[0.38466914 0.02127198 0.15402923]
 [0.42176461 0.33728669 0.98393754]
 [0.03348315 0.22869189 0.75957876]]


Este é um tensor 1's de tamanho 10
[[[0.81715636 0.36629727 0.14953991]
  [0.81934575 0.87991751 0.66122873]
  [0.22901819 0.95842333 0.62625001]]

 [[0.23859597 0.26688955 0.38275373]
  [0.2977896  0.81685567 0.24292174]
  [0.49427596 0.75894422 0.22528918]]

 [[0.90511409 0.5463602  0.65369624]
  [0.52892477 0.43674823 0.8325517 ]
  [0.21729178 0.76828771 0.8839808 ]]]


#**NUMPY - 7º Ordenar e Adicionar num array**




In [ ]:
import numpy as np
rng = np.random.default_rng()
array_rng1 = rng.random((2,3))
#Ordenação
print("\nArray SEM ordenação")
print(array_rng1)
array_ordenado = np.sort(array_rng1)
print("\nArray COM ordenação")
print(array_ordenado)
#Concatenação
array_rng2 = rng.random((2,1))
print("\nArray 2 tamanho 1 por 3")
print(array_rng2)
array_concatenado = np.concatenate((array_ordenado,array_rng2), axis=1)
print("\n 1º Maneira de concatenar entre arrays")
print(array_concatenado)

array_concatenado2 = np.hstack((array_ordenado,array_rng2))
print("\n 2º Maneira de concatenar entre arrays")
print(array_concatenado2)


Array SEM ordenação
[[0.42530521 0.01010025 0.68430982]
 [0.36739922 0.25529937 0.15419137]]

Array COM ordenação
[[0.01010025 0.42530521 0.68430982]
 [0.15419137 0.25529937 0.36739922]]

Array 2 tamanho 1 por 3
[[0.23287883]
 [0.89576934]]

 1º Maneira de concatenar entre arrays
[[0.01010025 0.42530521 0.68430982 0.23287883]
 [0.15419137 0.25529937 0.36739922 0.89576934]]

 2º Maneira de concatenar entre arrays
[[0.01010025 0.42530521 0.68430982 0.23287883]
 [0.15419137 0.25529937 0.36739922 0.89576934]]


#**NUMPY - 8 Como saber o formato de um array**

In [ ]:
import numpy as np
rng = np.random.default_rng()
array_rng1 = rng.random((12,23,24))
print(array_rng1)


print("\nO número de dimensões")
print(array_rng1.ndim)
print("\nO número de elementos")
print(array_rng1.size)
print("\nO formato do array")
print(array_rng1.shape)

#**NUMPY - 9 Como mudar um formato de um array**
reshape/flatten/hsplit/vsplit

In [ ]:
import numpy as np
x = np.arange(0,20)
print("\nArray de 1 de dimensão")
print(x)
print(x.shape)

print("\nArray de 4 de dimensões")
x2 = np.reshape(x,(4,5))
print(x2)
print(x2.shape)

print("\nArray de 1 de dimensões de novo")
x3 = x2.flatten()
print(x3)
print(x3.shape)

print("\n 4 Array de 1 dimensão e 5 elementos ")
x4= np.hsplit(x3,5)
print(x4)
print(x4[0])

#**NUMPY - 10º Operações Matemáticas com um array**
soma/subtração/multiplicação/divisão

sum/min/max

In [ ]:
import numpy as np

x = np.array([[1,2,3],[6,5,3],[9,9,9]])
print(f"Array x\n {x}")

x = x + 2
print(f"\nSomar  cada elemente com  2\n {x}")


x = x - 5
print("\nSubtrair  cada elemente com  5")
print(x)


x = x * 4
print("\nMultiplicar cada elemente por  4")
print(x)


x = x / 2
print("\nDividir cada elemente por  2")
print(x)


y = np.arange(1,10)
y = np.reshape(y,(3,3))
print(f"\nArray y: \n{y}")

w = x + y
print(f'\n Array w: \n{w}')

w = x / y
print(f'\n Array w: \n{w}')

z = np.sum(y,axis=0)
print(f'\n Somatório na vertical y: \n{z}')

z = np.sum(y,axis=1)
print(f'\n Somatório na horizontal y: \n{z}')

z = np.sum(y)
print(f'\n Somatório y: \n{z}')

z = np.min(y)
print(f'\n Somatório y: \n{z}')

z = np.max(y)
print(f'\n Somatório y: \n{z}')



#**NUMPY - 11 Salvando um Array num Arquivo .txt**
Parâmetros fmt, dtype, delimiter

In [ ]:
import numpy as np

x = np.arange(27)
x = x.reshape((3,3,3))
print(f'tensor 3x3x3:\n {x}')

y = x.flatten()
print(f'\nvetor de 27 posições:\n {y}')
np.savetxt('arrayTeste.txt', y,fmt= '%d', delimiter = ';')

z= np.loadtxt('arrayTeste.txt',dtype = np.int8 ,delimiter = ';',)

print(f'\narquivo recuperado e carregado para dentro do programa:\n {z} \ncom o seguinte tipo de dado: {(z.dtype)}')

tensor 3x3x3:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

vetor de 27 posições:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

arquivo recuperado e carregado para dentro do programa:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 
com o seguinte tipo de dado: int8


#**PLOTLY - 1º Abrindo a Documentação da Bilioteca**

#**PLOTLY - 2º Criando arrays para montar os gráficos**

In [ ]:
import numpy as np

a = 3/4;
b = 2/4;
c = 1/4;
soma_a = np.ones(20);
soma_b = np.ones(20);
soma_c = np.ones(20);
for i in range (1,soma_a.size):
  soma_a[i] = soma_a[i-1] + a**i;
  soma_b[i] = soma_b[i-1] + b**i;
  soma_c[i] = soma_c[i-1] + c**i;

np.savetxt('soma_a.txt', soma_a,fmt= '%f', delimiter = ';')
np.savetxt('soma_b.txt', soma_b,fmt= '%f', delimiter = ';')
np.savetxt('soma_c.txt', soma_c,fmt= '%f', delimiter = ';')



# **PLOTLY - 3º Recuperando arquivos e plotando o primeiro gráfico**

In [ ]:
import numpy as np
import plotly.express as px
array_a_axis_y = np.loadtxt("soma_a.txt",dtype=np.float64, delimiter= ';')
fig = px.scatter(array_a_axis_y)
fig.show()

# **PLOTLY - 4º Recuperando arquivos e plotando os três gráficos gráfico**

In [ ]:
import numpy as np
import plotly.express as px
array_a_axis_y = np.loadtxt("soma_a.txt",dtype=np.float64, delimiter= ';')
array_b_axis_y = np.loadtxt("soma_b.txt",dtype=np.float64, delimiter= ';')
array_c_axis_y = np.loadtxt("soma_c.txt",dtype=np.float64, delimiter= ';')


array_abc_axis_y = np.vstack((array_a_axis_y,array_b_axis_y,array_c_axis_y))
print(array_abc_axis_y)
array_abc_axis_y = array_abc_axis_y.transpose()
print(array_abc_axis_y)
fig = px.line(array_abc_axis_y, labels= "teste",title="Somatório")
fig.show()

[[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
  3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
  3.969932 3.977449 3.983087 3.987315]
 [1.       1.5      1.75     1.875    1.9375   1.96875  1.984375 1.992188
  1.996094 1.998047 1.999023 1.999512 1.999756 1.999878 1.999939 1.999969
  1.999985 1.999992 1.999996 1.999998]
 [1.       1.25     1.3125   1.328125 1.332031 1.333008 1.333252 1.333313
  1.333328 1.333332 1.333333 1.333333 1.333333 1.333333 1.333333 1.333333
  1.333333 1.333333 1.333333 1.333333]]
[[1.       1.       1.      ]
 [1.75     1.5      1.25    ]
 [2.3125   1.75     1.3125  ]
 [2.734375 1.875    1.328125]
 [3.050781 1.9375   1.332031]
 [3.288086 1.96875  1.333008]
 [3.466064 1.984375 1.333252]
 [3.599548 1.992188 1.333313]
 [3.699661 1.996094 1.333328]
 [3.774746 1.998047 1.333332]
 [3.831059 1.999023 1.333333]
 [3.873295 1.999512 1.333333]
 [3.904971 1.999756 1.333333]
 [3.928728 1.999878 1.333333]
 [3.946546 1.999939

# **PLOTLY - 5º Utilizando plotly.graph_objects**


In [ ]:
import numpy as np
import plotly.graph_objects as go
array_a_axis_y = np.loadtxt("soma_a.txt",dtype=np.float64, delimiter= ';')
array_b_axis_y = np.loadtxt("soma_b.txt",dtype=np.float64, delimiter= ';')
array_c_axis_y = np.loadtxt("soma_c.txt",dtype=np.float64, delimiter= ';')

array_axis_x = np.arange(1,array_a_axis_y.size)
fig = go.Figure()
fig.add_trace(go.Scatter(x= array_axis_x, y= array_a_axis_y,mode='lines', name='Série de 3/4'))
fig.add_trace(go.Scatter(x= array_axis_x, y= array_b_axis_y,mode='markers', name='Série de 2/4'))
fig.add_trace(go.Scatter(x= array_axis_x, y= array_c_axis_y,mode='markers+lines', name='Série de 1/4'))
fig.update_layout(title = "Somatório de Series com frações",
                  xaxis_title = "termos",
                  yaxis_title = "valor")
fig.show()